### ISSUE TITLE
Can't receive incoming video calls between Android and Web

### ISSUE THREAD

**Issue by mnesarco** [QuickBlox/quickblox-javascript-sdk#21]
VideoCall from Web to Android Works, but call from Android to Web is never accepted (in web) shows the incoming call dialog but does not accept the call.

Web sends the Accept package:
```xml
<message from="3907665-24969@chat.quickblox.com/1220770403-quickblox-262028" to="3891234-24969@chat.quickblox.com" type="headline" id="55940a0f0ba71a5e54000000" xmlns="jabber:client">
<extraParams xmlns="jabber:client">
<moduleIdentifier>WebRTCVideoChat</moduleIdentifier>
<signalType>accept</signalType>
<sessionID>1fadfb11-8737-4d70-8923-745989fc3cf1</sessionID>
<sdp>v=0
o=- 4622867165379984168 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS bHzg5kjvzRCf5oKqRMW7Sppz2hmtoCqAQ6dE
m=audio 52993 RTP/SAVPF 103 111 9 0 8 106 105 13 126
c=IN IP4 192.168.1.7
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2795255774 1 udp 2122260223 192.168.1.7 52993 typ host generation 0
a=ice-ufrag:SYho//LKyMjDZ/Om
a=ice-pwd:JvxF4mfUlbOZGjeZNYN8TN5p
a=fingerprint:sha-256 0A:9E:F2:C3:2F:8D:E1:37:72:47:5C:6F:A4:9F:66:6A:72:27:C9:9A:30:54:42:20:D7:73:F8:9B:F6:63:8B:AF
a=setup:active
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:103 ISAC/16000
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:1387731595 cname:354hfWjE1NEnozxI
a=ssrc:1387731595 msid:bHzg5kjvzRCf5oKqRMW7Sppz2hmtoCqAQ6dE 609fa510-5809-4564-84c3-4fd65f51a515
a=ssrc:1387731595 mslabel:bHzg5kjvzRCf5oKqRMW7Sppz2hmtoCqAQ6dE
a=ssrc:1387731595 label:609fa510-5809-4564-84c3-4fd65f51a515
m=video 52993 RTP/SAVPF 100 116 117 96
c=IN IP4 192.168.1.7
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2795255774 1 udp 2122260223 192.168.1.7 52993 typ host generation 0
a=ice-ufrag:SYho//LKyMjDZ/Om
a=ice-pwd:JvxF4mfUlbOZGjeZNYN8TN5p
a=fingerprint:sha-256 0A:9E:F2:C3:2F:8D:E1:37:72:47:5C:6F:A4:9F:66:6A:72:27:C9:9A:30:54:42:20:D7:73:F8:9B:F6:63:8B:AF
a=setup:active
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=ssrc-group:FID 260444606 3557108921
a=ssrc:260444606 cname:354hfWjE1NEnozxI
a=ssrc:260444606 msid:bHzg5kjvzRCf5oKqRMW7Sppz2hmtoCqAQ6dE 9df8c788-c61f-4898-b33f-f29c7e31856d
a=ssrc:260444606 mslabel:bHzg5kjvzRCf5oKqRMW7Sppz2hmtoCqAQ6dE
a=ssrc:260444606 label:9df8c788-c61f-4898-b33f-f29c7e31856d
a=ssrc:3557108921 cname:354hfWjE1NEnozxI
a=ssrc:3557108921 msid:bHzg5kjvzRCf5oKqRMW7Sppz2hmtoCqAQ6dE 9df8c788-c61f-4898-b33f-f29c7e31856d
a=ssrc:3557108921 mslabel:bHzg5kjvzRCf5oKqRMW7Sppz2hmtoCqAQ6dE
a=ssrc:3557108921 label:9df8c788-c61f-4898-b33f-f29c7e31856d
</sdp>
<platform>web</platform>
</extraParams></message>
 ```

But in the android side, an exception is thrown:

```
07-01 10:41:50.471  10394-16555/com.quickblox.sample.videochatwebrtcnew E/XMPPConnection﹕ Exception in packet listener
    java.lang.NumberFormatException: Invalid int: ""
            at java.lang.Integer.invalidInt(Integer.java:137)
            at java.lang.Integer.parseInt(Integer.java:358)
            at java.lang.Integer.parseInt(Integer.java:331)
            at java.lang.Integer.valueOf(Integer.java:489)
            at com.quickblox.videochat.webrtc.RTCSignallingMessageProcessor.createSessionDescription(RTCSignallingMessageProcessor.java:187)
            at com.quickblox.videochat.webrtc.RTCSignallingMessageProcessor.processVideoAudioChatMessage(RTCSignallingMessageProcessor.java:108)
            at com.quickblox.videochat.webrtc.RTCSignallingMessageProcessor.processSignalMessage(RTCSignallingMessageProcessor.java:79)
            at com.quickblox.chat.QBWebRTCSignaling.deliver(QBWebRTCSignaling.java:93)
            at com.quickblox.chat.QBVideoChatWebRTCSignalingManager.deliverMessage(QBVideoChatWebRTCSignalingManager.java:173)
            at com.quickblox.chat.QBVideoChatWebRTCSignalingManager.access$100(QBVideoChatWebRTCSignalingManager.java:19)
            at com.quickblox.chat.QBVideoChatWebRTCSignalingManager$1.processPacket(QBVideoChatWebRTCSignalingManager.java:56)
            at org.jivesoftware.smack.XMPPConnection$ListenerWrapper.notifyListener(XMPPConnection.java:1233)
            at org.jivesoftware.smack.XMPPConnection$ListenerNotification.run(XMPPConnection.java:1143)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```

**Comment by soulfly** [comment]
Which version of Android SDK do you use? the latest 2.2.5 ?

**Comment by mnesarco** [comment]
Yes, I am using the latest 2.2.5

On Mon, Jul 6, 2015 at 6:59 AM, Igor Khomenko <notifications@github.com>
wrote:

> Which version of Android SDK do you use? the latest 2.2.5 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QuickBlox/quickblox-javascript-sdk/issues/21#issuecomment-118832975>
> .
>



-- 
Frank D. Martínez M.

**Comment by soulfly** [comment]
Thanks, let us do some tests on our side and let you know about the results and possible issue

**Comment by soulfly** [comment]
Just checked with 2.2.6 - works fine on both sides
