### ISSUE TITLE
integrate quickblox with ionic 2

### ISSUE THREAD

**Issue by mironcaius** [QuickBlox/quickblox-javascript-sdk#220]
Hello,
I am trying to make the javascript SDK work with ionic 2 but I am missing something.
This sample works on my android device
https://quickblox.com/developers/Sample-webrtc-cordova
but the amount of code there and lack of documentation makes it impossible for me to reuse anything from there.

So i tried to add the init QB after the platform is ready.

```
initializeApp() {
    var that = this;
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();

      //     var QuickBlox = quickblox.QuickBlox;
//     var QB1 = new QuickBlox();
// var QB2 = new QuickBlox();
// console.log( QB1 );

var CREDENTIALS = {
  appId: 28287,
  authKey: 'XydaWcf8OO9xhGT',
  authSecret: 'JZfqTspCvELAmnW'
};

var CONFIG = {
  endpoints: {
    api: "apicustomdomain.quickblox.com", // set custom API endpoint
    chat: "chatcustomdomain.quickblox.com" // set custom Chat endpoint
  },
  chatProtocol: {
    active: 2 // set 1 to use BOSH, set 2 to use WebSockets (default)
  },
  debug: {mode: 1} // set DEBUG mode
};

QB.init(CREDENTIALS.appId, CREDENTIALS.authKey, CREDENTIALS.authSecret, CONFIG);

```

**Environment details**
"quickblox": "^2.5.2",
ionic --version
2.2.1
npm --version
4.4.4

**Did this work before?**
No

**Expected behavior**
To make it work as the cordova example

**Logs**

`            (http://192.168.0.132:8101/build/main.js:207192:20) at http://192.168.0.132:8101/build/main.js:145757:64 at
            t.invoke (http://192.168.0.132:8101/build/polyfills.js:3:9094) at Object.onInvoke
            (http://192.168.0.132:8101/build/main.js:62855:37) at t.invoke
            (http://192.168.0.132:8101/build/polyfills.js:3:9045) at e.run
            (http://192.168.0.132:8101/build/polyfills.js:3:6481) at http://192.168.0.132:8101/build/polyfills.js:3:4583
            at t.invokeTask (http://192.168.0.132:8101/build/polyfills.js:3:9723)
[22:31:51]  console.error: ORIGINAL STACKTRACE:  MEM: 930.6MB
[22:31:51]  console.error: Error: Uncaught (in promise): ReferenceError: Strophe is not defined ReferenceError: Strophe  MEM: 930.6MB
            is not defined at Object.<anonymous> (http://192.168.0.132:8101/build/main.js:197070:5) at
            __webpack_require__ (http://192.168.0.132:8101/build/main.js:20:30) at QuickBlox.init
            (http://192.168.0.132:8101/build/main.js:207192:20) at http://192.168.0.132:8101/build/main.js:145757:64 at
            t.invoke (http://192.168.0.132:8101/build/polyfills.js:3:9094) at Object.onInvoke
            (http://192.168.0.132:8101/build/main.js:62855:37) at t.invoke
            (http://192.168.0.132:8101/build/polyfills.js:3:9045) at e.run
            (http://192.168.0.132:8101/build/polyfills.js:3:6481) at http://192.168.0.132:8101/build/polyfills.js:3:4583
            at t.invokeTask (http://192.168.0.132:8101/build/polyfills.js:3:9723) at s
            (http://192.168.0.132:8101/build/polyfills.js:3:4211) at http://192.168.0.132:8101/build/polyfills.js:3:4612
            at t.invokeTask (http://192.168.0.132:8101/build/polyfills.js:3:9723) at Object.onInvokeTask
            (http://192.168.0.132:8101/build/main.js:62846:37) at t.invokeTask
            (http://192.168.0.132:8101/build/polyfills.js:3:9659) at e.runTask
            (http://192.168.0.132:8101/build/polyfills.js:3:7083) at i
            (http://192.168.0.132:8101/build/polyfills.js:3:3671)`

**Comment by mironcaius** [comment]
I managed to make this work. For future reference and documentation, this is how i made it work. 
I added this in index.html inside the ionic project
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

  <script>
      document.addEventListener('deviceready', onDeviceReady, false);

      function onDeviceReady() {
          console.log("onDeviceReady");

          // Just for iOS devices.
          // Read more here https://github.com/eface2face/cordova-plugin-iosrtc
          if (window.device.platform === 'iOS') {
              cordova.plugins.iosrtc.registerGlobals();
          }else if (window.device.platform === 'Android') {
            //
          }

          // Load JavaScript files async
          //
          var loadScriptAsync = function(path){
              var jsScript = document.createElement("script");
              jsScript.type = "text/javascript";
              jsScript.async = false; //async is being set to false so that script will not immediately fire.
              jsScript.src = path;
              document.getElementsByTagName("body")[0].appendChild(jsScript);
              console.log( "loadScriptAsync " + path);
          }
          // loadScriptAsync("https://cdnjs.cloudflare.com/ajax/libs/quickblox/2.5.0/quickblox.min.js");
          loadScriptAsync("https://cdnjs.cloudflare.com/ajax/libs/quickblox/2.4.0/quickblox.min.js");
          // loadScriptAsync("assets/quick/config.js")
          // loadScriptAsync("assets/quick/js/helpers.js")
          // loadScriptAsync("assets/quick/js/stateBoard.js")
          // loadScriptAsync("assets/quick/js/app.js")
      }

      // Listen for orientation changes and scroll
      //
      window.addEventListener('orientationchange', updatedVideoFrames);
      window.addEventListener('scroll', updatedVideoFrames);
      //
      function updatedVideoFrames(){
        if (window.device.platform === 'iOS') {
            cordova.plugins.iosrtc.refreshVideos();
        }
      }
    </script>
```

then in app.components.ts I added this on device ready:
```
var CONFIG = {
        'prod': {
          'appId': 40718,
          'authKey': 'AnB-JpA6r4y6RmS',
          'authSecret': '3O7Sr5Pg4Qjexwn'
        },
        'my': {
          'appId': 55324,
          'authKey': 'mjhFZnrS4aRzTLC',
          'authSecret': 'nGOHjerjZH-Hs34'
        },
        'test': {
          'appId': 39854,
          'authKey': 'JtensAa9y4AM5Yk',
          'authSecret': 'AsDFwwwxpr3LN5w'
        }
      };

      var CREDENTIALS = CONFIG.my;

      var CONFIG2 = {
        endpoints: {
          api: "apicustomdomain.quickblox.com", // set custom API endpoint
          chat: "chatcustomdomain.quickblox.com" // set custom Chat endpoint
        },
        chatProtocol: {
          active: 2 // set 1 to use BOSH, set 2 to use WebSockets (default)
        },
        debug: { mode: 1 } // set DEBUG mode
      };

      QB.init(
        CREDENTIALS.appId,
        CREDENTIALS.authKey,
        CREDENTIALS.authSecret,
        CONFIG2
      );

      var that = this;

      QB.createSession(function (err, result) {
        console.log("QB.createSession(");
        if (err) console.log(JSON.stringify(err));
        else {
          console.log(JSON.stringify(result));

          // var params = {login: 'garry', password: 'webAppPass'};

          // or through email
          var params = { email: 'garry@gmail.com', password: 'webAppPass' };


          // or through social networks (Facebook / Twitter)
          // var params = {provider: 'facebook', keys: {token: 'AM46dxjhisdffgry26282352fdusdfusdfgsdf'}};

          QB.login(params, function (err, result) {
            console.log("QB.login");
            if (err) {
              console.log(JSON.stringify(err));

              QB.users.create({
                'email': 'garry@gmail.com',
                'password': 'webAppPass',
                'full_name': 'caius',
                'tag_list': 'miron'
              }, function (createErr, createUser) {
                if (createErr) {
                  console.log('[create user] Error:', createErr);
                  // reject(createErr);
                } else {
                  console.log('[create user] xxxxx:');
                  console.log(JSON.stringify(createUser));
                  QB.login(params, function (reloginErr, reloginUser) {
                    if (reloginErr) {
                      console.log('[relogin user] Error:', reloginErr);
                    } else {
                      console.log('[relogin user] xxxxxxxx:');
                      console.log(JSON.stringify(reloginUser));
                      that.connectUser(reloginUser, CREDENTIALS);
                    }
                  });
                }
              });
            }
            else
              console.log(JSON.stringify(result));
              that.connectUser(result, CREDENTIALS);
          });
        }

      });

connectUser(reloginUser, CREDENTIALS) {
    console.log("connectUser " + QB.chat.helpers.getUserJid(reloginUser.id, CREDENTIALS.appId))
    // QB.chat.connect({ jid: QB.chat.helpers.getUserJid(reloginUser.id, CREDENTIALS.appId), password: "webAppPass" }, function (err, roster) {
    //   if (err) {
    //     console.log("geremy67df eerrr");
    //   } else {
    //     console.log("geremy67df ssssssss");
    //   }
    // });

    QB.chat.connect({ userId:reloginUser.id, password: "webAppPass" }, function (err, roster) {
      if (err) {
        console.log("geremy67df eerrr");
      } else {
        console.log("geremy67df ssssssss");
      }
    });
    // var calleesIds = [25474014]; // User's ids
    // var sessionType = QB.webrtc.CallType.VIDEO; // AUDIO is also possible

    // var session = QB.webrtc.createNewSession(calleesIds, sessionType);

    // var mediaParams = {
    //   audio: true,
    //   video: true,
    //   options: {
    //     muted: true,
    //     mirror: true
    //   },
    //   elemId: 'localVideo'
    // };

    // session.getUserMedia(mediaParams, function (err, stream) {
    //   if (err) {
    //     console.log(err);
    //     console.log("eerrr");
    //   } else {
    //     console.log("ssssssss");
    //   }
    // });
  }
```

The login works but when i try to call QB.chat it connects and disconnects indefintly:
```
[10:16:20]  error opening ws message: {"category":"console","type":"log","data":["[ChatProxy]","Chat Protocol -  MEM: 344.9MB
            WebSocket"]}
[10:16:22]  error opening ws message: {"category":"console","type":"log","data":["[undefined]","error:  MEM: 344.9MB
            ","Status.CONNFAIL - The connection attempt failed"]}
[10:16:22]  error opening ws message: {"category":"console","type":"log","data":["[ChatProxy]","Status.DISCONNECTED at  MEM: 344.9MB
            10:16:22"]}
[10:16:22]  error opening ws message:  MEM: 344.9MB
            {"category":"console","type":"log","data":["[ChatProxy]","connect",{"userId":25518374,"password":"webAppPass"}]}
[10:16:22]  error opening ws message: {"category":"console","type":"log","data":["[ChatProxy]","Status.CONNECTING"]}  MEM: 344.9MB
[10:16:22]  error opening ws message: {"category":"console","type":"log","data":["[ChatProxy]","Chat Protocol -  MEM: 345.1MB
            WebSocket"]}
```

What i am doing wrong ?

**Comment by Vladlukhanin** [comment]
Hi, @mironcaius !

Did you use the config like wrote in here? Did you change endpoints?
```
var CONFIG2 = {
        endpoints: {
          api: "apicustomdomain.quickblox.com", // set custom API endpoint
          chat: "chatcustomdomain.quickblox.com" // set custom Chat endpoint
        },
        chatProtocol: {
          active: 2 // set 1 to use BOSH, set 2 to use WebSockets (default)
        },
        debug: { mode: 1 } // set DEBUG mode
      };
```
"apicustomdomain.quickblox.com" and "chatcustomdomain.quickblox.com" it's just an example.
Set "api.quickblox.com" and "chat.quickblox.com" instead, if you want to develop in our production server.

**Comment by arsewizz** [comment]
sameone cana share a exemple who works?

**Comment by niccolofanton** [comment]
@arsewizz  https://github.com/niccolofanton/quickblox-ionic3 try this

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/js-video-calling](https://docs.quickblox.com/docs/js-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
