### ISSUE TITLE
Unable to submit pull request because gh-pages fails unit tests before edits.

### ISSUE THREAD

**Issue by ruffin--** [QuickBlox/quickblox-javascript-sdk#236]
**Environment details**
*(Operating system, browser information, SDK version)*

Hitting SpecRunner.html with Chrome 58.0.3029.96 (64-bit)

**Did this work before?**

Unsure

**Expected behavior**

All tests pass after pulling gh-pages with no edits performed.

**Actual behavior**

```
94 specs, 4 failures, 1 pending spec
Spec List | Failures
Chat API REST API can delete a message with id
Expected Object({ code: 0, status: 'error', message: '', detail: undefined }) to be null.
Error: Expected Object({ code: 0, status: 'error', message: '', detail: undefined }) to be null.
    at stack (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1577:17)
    at buildExpectationResult (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1547:14)
    at Spec.expectationResultFactory (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:638:18)
    at Spec.addExpectationResult (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:330:34)
    at Expectation.addExpectationResult (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:588:21)
    at Expectation.toBeNull (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1501:12)
    at file:///C:/Projects/quickblox-javascript-sdkPR/spec/QB-ChatSpec.js:470:29
    at n.handleResponse (file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:47:1534)
    at Object.error (file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:47:2525)
    at l (file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:45:27736)
Users API Get Users can get users by login
Failed: Get user by login error: {"code":401,"status":"error","message":"Unauthorized","detail":"{\"errors\":{\"base\":[\"Auth fail\"]}}"}
Error: Failed: Get user by login error: {"code":401,"status":"error","message":"Unauthorized","detail":"{\"errors\":{\"base\":[\"Auth fail\"]}}"}
    at stack (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1577:17)
    at buildExpectationResult (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1547:14)
    at Spec.expectationResultFactory (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:638:18)
    at Spec.addExpectationResult (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:330:34)
    at Env.fail (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:987:25)
    at Function.next.fail (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1903:19)
    at file:///C:/Projects/quickblox-javascript-sdkPR/spec/QB-UsersSpec.js:138:16
    at file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:44:15401
    at n.handleResponse (file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:47:1534)
    at Object.error (file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:47:2525)
Users API Get Users can get users by email
Failed: Get user by email error: {"code":401,"status":"error","message":"Unauthorized","detail":"{\"errors\":{\"base\":[\"Required session does not exist\"]}}"}
Error: Failed: Get user by email error: {"code":401,"status":"error","message":"Unauthorized","detail":"{\"errors\":{\"base\":[\"Required session does not exist\"]}}"}
    at stack (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1577:17)
    at buildExpectationResult (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1547:14)
    at Spec.expectationResultFactory (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:638:18)
    at Spec.addExpectationResult (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:330:34)
    at Env.fail (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:987:25)
    at Function.next.fail (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1903:19)
    at file:///C:/Projects/quickblox-javascript-sdkPR/spec/QB-UsersSpec.js:153:16
    at file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:44:15401
    at n.handleResponse (file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:47:1534)
    at Object.error (file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:47:2525)
Users API Get Users can get users by id
Failed: Get user by id error: {"code":401,"status":"error","message":"Unauthorized","detail":"{\"errors\":{\"base\":[\"Required session does not exist\"]}}"}
Error: Failed: Get user by id error: {"code":401,"status":"error","message":"Unauthorized","detail":"{\"errors\":{\"base\":[\"Required session does not exist\"]}}"}
    at stack (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1577:17)
    at buildExpectationResult (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1547:14)
    at Spec.expectationResultFactory (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:638:18)
    at Spec.addExpectationResult (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:330:34)
    at Env.fail (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:987:25)
    at Function.next.fail (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1903:19)
    at file:///C:/Projects/quickblox-javascript-sdkPR/spec/QB-UsersSpec.js:168:16
    at file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:44:15401
    at n.handleResponse (file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:47:1534)
    at Object.error (file:///C:/Projects/quickblox-javascript-sdkPR/quickblox.min.js:47:25
```

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by dimaspirit** [comment]
@ruffin-- , hi, we fixed this issues. Changes are in `develop` branch. Could you merge with develop branch and make pull request to `quickblox-javascript-sdk\develop` ?

**Comment by ruffin--** [comment]
Yep, works. Thanks!

**Comment by dimaspirit** [comment]
Thanks for your pull request
