### ISSUE TITLE
Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by shide1989** [QuickBlox/quickblox-javascript-sdk#252]
Hi,
in quickblox sdk 2.5.4 using NodeJS,
when calling `QB.chat.helpers.getRoomJidFromDialogId` we are getting the following error :
`TypeError: Cannot read property 'indexOf' of null`

**Did this work before?**
This used to work well in quickblox 2.4

**Environment details**
Running in NodeJS 8.1.0
*(Operating system, browser information, SDK version)*
QB sdk 2.5.4

**Expected behavior**
Expected to get the dialog JID

**Actual behavior**
Crash.

**Logs**
```
TypeError: Cannot read property 'indexOf' of null
at Helpers.getIdFromNode (/home/ec2-user/engine/node_modules/quickblox/src/modules/qbChat.js:2478:16)
at ChatProxy._onPresence (/home/ec2-user/engine/node_modules/quickblox/src/modules/qbChat.js:448:31)
at Client.<anonymous> (/home/ec2-user/engine/node_modules/quickblox/src/modules/qbChat.js:812:26)
at emitOne (events.js:120:20)
at Client.emit (events.js:210:7)
at Client._handleStanza (/home/ec2-user/engine/node_modules/node-xmpp-client/lib/Client.js:227:12)
at Client.onStanza (/home/ec2-user/engine/node_modules/node-xmpp-client/lib/Client.js:221:8)
at emitOne (events.js:115:13)
at Connection.emit (events.js:210:7)
at Connection.onStanza (/home/ec2-user/engine/node_modules/node-xmpp-core/lib/Connection.js:377:10)
at StreamParser.<anonymous> (/home/ec2-user/engine/node_modules/node-xmpp-core/lib/Connection.js:231:10)
at emitOne (events.js:115:13)
at StreamParser.emit (events.js:210:7)
at SaxLtx.<anonymous> (/home/ec2-user/engine/node_modules/@xmpp/streamparser/index.js:69:14)
at emitOne (events.js:115:13)
at SaxLtx.emit (events.js:210:7)
at SaxLtx._handleTagOpening (/home/ec2-user/engine/node_modules/ltx/lib/parsers/ltx.js:38:12)
at SaxLtx.write (/home/ec2-user/engine/node_modules/ltx/lib/parsers/ltx.js:127:18)
at StreamParser.write (/home/ec2-user/engine/node_modules/@xmpp/streamparser/index.js:134:17)
at Connection.onData (/home/ec2-user/engine/node_modules/node-xmpp-core/lib/Connection.js:310:17)
at emitOne (events.js:120:20)
at TLSSocket.emit (events.js:210:7)
at addChunk (_stream_readable.js:250:12)
at readableAddChunk (_stream_readable.js:237:11)
at TLSSocket.Readable.push (_stream_readable.js:195:10)
at TLSWrap.onread (net.js:588:20)
```

**Steps to reproduce the behavior**
`var jid = QB.chat.helpers.getRoomJidFromDialogId(dialog._id); //boom`

**Comment by shide1989** [comment]
any updates ?

**Comment by ManojSolanki** [comment]
Hi try call QB.init() each-time , you sending message like: 

```
QB.init();
QB.chat.connect(function(){
  QB.chat.send();

});
```

**Comment by Vladlukhanin** [comment]
TypeError: Cannot read property 'indexOf' of null  - from Helpers.getIdFromNode() as I see.
https://quickblox.github.io/quickblox-javascript-sdk/docs/QB.chat.helpers.html#.getIdFromNode.
You need to call QB.init() just once, to init your application.

**Comment by dimaspirit** [comment]
@shide1989 the previously answer helps you?
