### ISSUE TITLE
NativeScript Crashes

### ISSUE THREAD

**Issue by Izrab** [QuickBlox/quickblox-javascript-sdk#379]
I am making Core+XML+TS Android app with NativeScript (version 5.4.2), 
I want to make video call between users of my NativeScript apps.
I installed the quickblox javascript sdk package (version 2.12.3) to my app, 
and this is my code:

```
/*
In NativeScript, a file with the same name as an XML file is known as
a code-behind file. The code-behind is a great place to place your view
logic, and to set up your page’s data binding.
*/

import { NavigatedData, Page } from "tns-core-modules/ui/page";
// import { QB } from "quickblox"
var QB = require('quickblox');

import { HomeViewModel } from "./home-view-model";

export function onNavigatingTo(args: NavigatedData) {
    const page = <Page>args.object;

    var CREDENTIALS = {
        appId: 77897,
        authKey: 'fW8OsXc5tpvTq7d',
        authSecret: '2t42CHkmwxYdzqx'
    };
       
    QB.init(CREDENTIALS.appId, CREDENTIALS.authKey, CREDENTIALS.authSecret);
      
    page.bindingContext = new HomeViewModel();
}
```

But my app crashes when I open it and shows this **error log**:
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onViewAttachedToWindow failed
Error: java.lang.ClassNotFoundException: technology.master.nativescript.WebSocket
   java.lang.Class.classForName(Native Method)
   java.lang.Class.forName(Class.java:453)
   java.lang.Class.forName(Class.java:378)
   com.tns.Runtime.getClassForName(Runtime.java:1123)
   com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
   com.tns.Runtime.resolveClass(Runtime.java:679)
   com.tns.Runtime.callJSMethodNative(Native Method)
   com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
   com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
   com.tns.Runtime.callJSMethod(Runtime.java:1070)
   com.tns.Runtime.callJSMethod(Runtime.java:1050)
   com.tns.Runtime.callJSMethod(Runtime.java:1042)
   java.lang.Object_vendor_108564_36_AttachListener.onViewAttachedToWindow(Unknown Source:10)
   android.view.View.dispatchAttachedToWindow(View.java:20012)
   android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3589)
   android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
   android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
   android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
   android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
   android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
   android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2244)
   android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1909)
   android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8566)
   android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
   android.view.Choreographer.doCallbacks(Choreographer.java:761)
   android.view.Choreographer.doFrame(Choreographer.java:696)
   android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
   android.os.Handler.handleCallback(Handler.java:873)
   android.os.Handler.dispatchMessage(Handler.java:99)
   android.os.Looper.loop(Looper.java:214)
   android.app.ActivityThread.main(ActivityThread.java:7089)
   java.lang.reflect.Method.invoke(Native Method)
   com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
   com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.ClassNotFoundException: Didn't find class "technology.master.nativescript.WebSocket" on path: DexPathList[[zip file "/data/app/org.nativescript.Chatsaas-I17trclDPZnsZgTLllewkA==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.Chatsaas-I17trclDPZnsZgTLllewkA==/lib/arm64, /data/app/org.nativescript.Chatsaas-I17trclDPZnsZgTLllewkA==/base.apk!/lib/arm64-v8a, /system/lib64]]
   dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
   java.lang.ClassLoader.loadClass(ClassLoader.java:379)
   java.lang.ClassLoader.loadClass(ClassLoader.java:312)
   java.lang.Class.classForName(Native Method)
   java.lang.Class.forName(Class.java:453)
   java.lang.Class.forName(Class.java:378)
   com.tns.Runtime.getClassForName(Runtime.java:1123)
   com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
   com.tns.Runtime.resolveClass(Runtime.java:679)
   com.tns.Runtime.callJSMethodNative(Native Method)
   com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
   com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
   com.tns.Runtime.callJSMethod(Runtime.java:1070)
   com.tns.Runtime.callJSMethod(Runtime.java:1050)
   com.tns.Runtime.callJSMethod(Runtime.java:1042)
   java.lang.Object_vendor_108564_36_AttachListener.onViewAttachedToWindow(Unknown Source:10)
   android.view.View.dispatchAttachedToWindow(View.java:20012)
   android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3589)
   android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)

android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
   android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
   android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
   android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
   android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2244)
   android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1909)
   android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8566)
   android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
   android.view.Choreographer.doCallbacks(Choreographer.java:761)
   android.view.Choreographer.doFrame(Choreographer.java:696)
   android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
   android.os.Handler.handleCallback(Handler.java:873)
   android.os.Handler.dispatchMessage(Handler.java:99)
   android.os.Looper.loop(Looper.java:214)
   android.app.ActivityThread.main(ActivityThread.java:7089)
   java.lang.reflect.Method.invoke(Native Method)
   com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
   com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
File: "file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js, line: 38564, column: 59
StackTrace: 
    Frame: function:'../node_modules/nativescript-websockets/websockets.js', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 38564, column: 60
    Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 751, column: 30
    Frame: function:'fn', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 121, column: 20
    Frame: function:'../node_modules/nativescript-xmpp-client/lib/websockets.js', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 43457, column: 10
    Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 751, column: 30
    Frame: function:'fn', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 121, column: 20
    Frame: function:'../node_modules/nativescript-xmpp-client/lib/session.js', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 43238, column: 20
    Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 751, column: 30
    Frame: function:'fn', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 121, column: 20
    Frame: function:'../node_modules/nativescript-xmpp-client/lib/Client.js', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 39282, column: 15
    Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 751, column: 30
    Frame: function:'fn', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 121, column: 20
    Frame: function:'../node_modules/nativescript-xmpp-client/xmpp-client.js', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 43632, column: 18
    Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 751, column: 30
    Frame: function:'fn', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 121, column: 20
    Frame: function:'../node_modules/quickblox/src/modules/chat/qbChat.js', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 57194, column: 12
    Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 751, column: 30
    Frame: function:'fn', file:'file:///data/data/org.nativescript.Chatsaas/files/app/runtime.js', line: 121, column: 20
    Frame: function:'init', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 64787, column: 20
Frame: function:'onNavigatingTo', file:'file:///data/data/org.nativescript.Chatsaas/files/app/bundle.js', line: 208, column: 9
    Frame: function:'push.../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 91175, column: 23
    Frame: function:'push.../node_modules/tns-core-modules/ui/page/page-common.js.PageBase.onNavigatingTo', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 113161, column: 14
    Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase._onNavigatingTo', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 108183, column: 37
    Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase.performNavigation', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 108155, column: 14
    Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase._processNextNavigationEntry', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 108147, column: 22
    Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.Frame._processNextNavigationEntry', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 108683, column: 58
    Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.Frame._onAttachedToWindow', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 108658, column: 14
    Frame: function:'AttachListener.onViewAttachedToWindow', file:'file:///data/data/org.nativescript.Chatsaas/files/app/vendor.js', line: 108570, column: 27
    at com.tns.Runtime.callJSMethodNative(Native Method)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
    at com.tns.Runtime.callJSMethod(Runtime.java:1070)
    at com.tns.Runtime.callJSMethod(Runtime.java:1050)
    at com.tns.Runtime.callJSMethod(Runtime.java:1042)
    at java.lang.Object_vendor_108564_36_AttachListener.onViewAttachedToWindow(Unknown Source:10)
    at android.view.View.dispatchAttachedToWindow(View.java:20012)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3589)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2244)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1909)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8566)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
    at android.view.Choreographer.doFrame(Choreographer.java:696)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7089)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.ClassNotFoundException: technology.master.nativescript.WebSocket
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:453)
    at java.lang.Class.forName(Class.java:378)
    at com.tns.Runtime.getClassForName(Runtime.java:1123)
    at com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
    at com.tns.Runtime.resolveClass(Runtime.java:679)
    ... 28 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "technology.master.nativescript.WebSocket" on path: DexPathList[[zip file "/data/app/org.nativescript.Chatsaas-I17trclDPZnsZgTLllewkA==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.Chatsaas-I17trclDPZnsZgTLllewkA==/lib/arm64, /data/app/org.nativescript.Chatsaas-I17trclDPZnsZgTLllewkA==/base.apk!/lib/arm64-v8a, /system/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    ... 34 more
```

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new samples:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat)

If it is still relevant after reviewing the updated information, feel free to open a new issue.
